CREATE TABLE [dbo].[RdxDevice] (
    [ID]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [DateLoaded]       DATETIME      DEFAULT (getdate()) NULL,
    [DateAdded]        DATETIME      NULL,
    [DateUpdated]      DATETIME      NULL,
    [DeviceID]         VARCHAR (100) NULL,
    [DeviceIP]         VARCHAR (100) NULL,
    [OemName]          VARCHAR (100) NULL,
    [OemModel]         VARCHAR (100) NULL,
    [OemSerialNumber]  VARCHAR (100) NULL,
    [DeviceModel]      VARCHAR (100) NULL,
    [OSVersionFull]    VARCHAR (100) NULL,
    [OSBranch]         VARCHAR (100) NULL,
    [OSBuildNumber]    VARCHAR (100) NULL,
    [OSInstallDate]    VARCHAR (100) NULL,
    [OSOobeDateTime]   DATETIME      NULL,
    [Latitude]         VARCHAR (100) NULL,
    [Longitude]        VARCHAR (100) NULL,
    [AccuracyKM]       VARCHAR (100) NULL,
    [Source]           VARCHAR (100) NULL,
    [FirstOnlineDate]  DATETIME      NULL,
    [LastOnlineDate]   DATETIME      NULL,
    [Retailer]         VARCHAR (100) NULL,
    [Rac]              VARCHAR (100) NULL,
    [Sku]              VARCHAR (100) NULL,
    [StoreID]          VARCHAR (100) NULL,
    [DeviceName]       VARCHAR (100) NULL,
    [Mdc1DeviceFamily] VARCHAR (100) NULL,
    [Mdc2FormFactor]   VARCHAR (100) NULL,
    [IsRetailPhone]    VARCHAR (100) NULL,
    [StoreNumber]      INT           NULL,
    CONSTRAINT [PK_RdxDevice_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

