CREATE TABLE [dbo].[InputRsitAppInstall] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [AsaSysTime]      DATETIME      NULL,
    [SqlSysTime]      DATETIME      DEFAULT (getdate()) NULL,
    [EventTime]       DATETIME      NULL,
    [EventDate]       DATE          NULL,
    [EventName]       VARCHAR (100) NULL,
    [EventCount]      INT           NULL,
    [DeviceType]      VARCHAR (50)  NULL,
    [DeviceOSVersion] VARCHAR (50)  NULL,
    [DeviceBrowser]   VARCHAR (50)  NULL,
    [SessionId]       VARCHAR (50)  NULL,
    [UserAnonId]      VARCHAR (50)  NULL,
    [OperationId]     VARCHAR (50)  NULL,
    [ClientIp]        VARCHAR (50)  NULL,
    [Continent]       VARCHAR (50)  NULL,
    [Country]         VARCHAR (50)  NULL,
    [Province]        VARCHAR (50)  NULL,
    [City]            VARCHAR (50)  NULL,
    [AppName]         VARCHAR (50)  NULL,
    [AppPlatformId]   VARCHAR (50)  NULL,
    [AppPlatformName] VARCHAR (50)  NULL,
    [AppCategoryId]   VARCHAR (50)  NULL,
    [AppCategoryName] VARCHAR (500) NULL,
    [StoreNumber]     VARCHAR (50)  NULL,
    [AppStoreName]    VARCHAR (50)  NULL,
    [AppUserId]       VARCHAR (50)  NULL,
    [Processed]       INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

